#ifndef _EVENT_PARAMETER_DEFS_H_
#define _EVENT_PARAMETER_DEFS_H_


REGISTER_EVENT_PARAMETER( x )
REGISTER_EVENT_PARAMETER( y )
REGISTER_EVENT_PARAMETER( angle )
REGISTER_EVENT_PARAMETER( player_id )


#endif // _EVENT_PARAMETER_DEFS_H_
